<?php


namespace app\modulse\admin\controllers;


use app\models\User;
use Yii;
use yii\data\ActiveDataProvider;
use yii\helpers\Url;

class UsersController extends AdminPanelController
{
    public function beforeAction($action)
    {
        Yii::$app->getView()->params['leftMenu'] = [
            ['label' =>'Пользователи', 'url' => Url::toRoute('users/index')],
            ['label' =>'Роли', 'url' => Url::toRoute('users/role')],
            ['label' =>'Разрешения', 'url' => Url::toRoute('users/permission-list')],
        ];
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => User::find(),
                'pagination' => [
                    'pageSize' => 20,
                    ],
                ]
        );
        return $this->render('index',compact('dataProvider'));
    }

    public function actionDelete($id)
    {
       User::findIdentity($id)->delete();
       (Yii::$app->authManager)->revokeAll($id);
       $this->redirect('index');
    }

    public function actionPermissionList()
    {
        return $this->render('permissionList');
    }

    public function actionRole()
    {
        return $this->render('role');
    }

}
